services:
  db:
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=${POSTGRES_DB:-postgres}
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  db-backup:
    image: schickling/postgres-backup-s3
    restart: always
    environment:
      - SCHEDULE=@weekly
      - S3_PREFIX=database-backups
    env_file: .env
    depends_on:
      - db

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "5050:5050"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
      - pgadmin
    networks:
      - default
      - web

  backend:
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@pgbouncer:5432/${POSTGRES_DB:-postgres}
    depends_on:
      - pgbouncer

  frontend:
    restart: always
    environment:
      - BACKEND_URL=http://backend:8000
      - PUBLIC_BACKEND_URL=http://backend:8000
      - BODY_SIZE_LIMIT=Infinity
    env_file: .env


networks:
  web:
    external: true

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
