services:
  db:
    ports:
      - "5432:5432"
  backend:
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data

  frontend-streamlit:
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    environment:
      - API_URL=http://backend:8000
      - PUBLIC_API_URL=http://localhost:8000 # Use localhost for dev access if needed outside docker network

  frontend:
    ports:
      - '5173:5173'
    volumes:
      - ./frontend-svelte:/app/frontend-svelte
      - ./shared:/app/shared
    environment:
      - BACKEND_URL=http://backend:8000
      - PUBLIC_BACKEND_URL=http://localhost:8000

volumes:
  postgres_data:
