services:
  db:
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  db-backup:
    image: schickling/postgres-backup-s3
    restart: always
    environment:
      - SCHEDULE=@weekly
      - S3_PREFIX=database-backups
    env_file: .env
    depends_on:
      - db

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5050:5050"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
      - pgadmin

  backend:
    restart: always

  frontend:
    restart: always
    environment:
      - BACKEND_URL=http://backend:8000
      - PUBLIC_BACKEND_URL=http://backend:8000
      - BODY_SIZE_LIMIT=Infinity
    env_file: .env


volumes:
  postgres_data:
  caddy_data:
  caddy_config:
