FROM node:22-alpine AS builder

WORKDIR /app
COPY frontend-svelte/ui/package*.json ./
RUN npm install

COPY frontend-svelte/ui .
RUN npm run build
RUN npm prune --omit=dev

FROM node:22-alpine

WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY frontend-svelte/ui/package.json .

EXPOSE 3000
ENV NODE_ENV=production

CMD ["node", "build"]
