name: Deploy to infomaniak

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Infomaniak via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get -y upgrade
            cd /home/debian/ScoreAI
            git pull origin main
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "MODEL=google-gla:gemini-2.5-flash-lite" >> .env
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
            echo "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}" >> .env
            echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env
            echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env
            echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
            docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up --build -d
            # run alembic migration
            docker exec --workdir /app/backend backend alembic upgrade head
