name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest


    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        code: ["backend", "shared"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        sudo apt-get install poppler-utils
        uv sync --frozen
    - name: Run tests
      run: uv run --frozen --project ${{ matrix.code }} --directory ${{ matrix.code }} pytest
    - name: Ruff format check
      run: uv run --frozen ruff format --check ${{ matrix.code }}
    - name: Ruff lint
      run: uv run --frozen ruff check ${{ matrix.code }}
    - name: Run mypy
      run: uv run --frozen --project ${{ matrix.code }} --directory ${{ matrix.code }} mypy .
